const items = [
	{
		img: "01.png",
		name: "Grey Nike Air Force1",
		price: "800",
		number: "5",
		category: "unisex",
		rating: "1200",
		size: "42",
		color: "#f8f8f8",
	},
	{
		img: "02.png",
		name: "Mesh Summer Shirt",
		price: "90",
		number: "5",
		category: "men",
		rating: "1400",
		size: "L",
		color: "hsl(210, 36%, 96%)",
	},
	{
		img: "03.png",
		name: "Neck Short Sleeve-Short set",
		price: "500",
		number: "5",
		category: "men",
		rating: "1050",
		size: "M",
		color: "yellow",
	},
	{
		img: "04.png",
		name: "Multi Pocket Jean",
		price: "300",
		number: "5",
		category: "women",
		rating: "230",
		size: "M",
		color: "black",
	},
	{
		img: "05.png",
		name: "Zipper Pocket Cargo Jeans",
		price: "350",
		number: "5",
		category: "women",
		rating: "500",
		size: "L",
		color: "blue",
	},
	{
		img: "06.png",
		name: "Pink CLean Up Cap",
		price: "50",
		number: "4",
		category: "female",
		rating: "45",
		size: "S",
		color: "pink",
	},
	{
		img: "07.png",
		name: "Bucket Hat",
		price: "60",
		number: "5",
		category: "unisex",
		rating: "1000",
		size: "S",
		color: "#fff",
	},
	{
		img: "08.png",
		name: "Floral Kids Dress",
		price: "70",
		number: "5",
		category: "kids",
		rating: "300",
		size: "S",
		color: "#848383",
	},
	{
		img: "09.png",
		name: "Knit Top mini Skirt Set",
		price: "200",
		number: "5",
		category: "women",
		rating: "1700",
		size: "S",
		color: "brown",
	},
	{
		img: "10.png",
		name: "crop Top Sweatpants Baggy Pants",
		price: "400",
		number: "5",
		category: "women",
		rating: "2060",
		size: "pink",
		color: "M",
	},
	{
		img: "11.png",
		name: "Toddler boy outfits Set",
		price: "100",
		number: "5",
		category: "kids",
		rating: "10",
		size: "XL",
		color: "",
	},
	{
		img: "12.png",
		name: "Leather Bag",
		price: "800",
		number: "5",
		category: "women",
		rating: "4200",
		size: "L",
		color: "hsl(209, 23%, 60%)",
	},
];
export default items;
